[package]
name = "dupl-server-proto-clib"
version = "0.1.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "*"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
dupl_server_proto = { path = "dupl-server-proto" }
